FROM golang:alpine AS builder

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /

ADD . /

RUN go build -ldflags="-s -w" -o /server ./main.go

FROM scratch
COPY --from=builder /server ./
ENTRYPOINT [ "./server" ]